### ISSUE TITLE
Unable to use custom configuration with reverse proxy

### ISSUE THREAD

**Issue by axeleroy** [bunkerity/bunkerized-nginx#127]
Hello,

I'm using bunkeriezd-nginx as a reverse proxy in front of multiple servers. One of them requires a custom Nginx configuration in order to work properly, so I followed the [multisite-custom-server-confs](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples/multisite-custom-server-confs) example and adapted to my usecase as follow:

```nginx
# /path/to/server-confs/app1.domain.com/site.conf
location / {
  proxy_buffering off;
  proxy_cache off;
  proxy_http_version 1.1;
  chunked_transfer_encoding off;
  proxy_set_header Connection '';
}
```

```
docker run ... -v /path/to/server-confs:/server-confs:ro ... \
-e MULTISITE=yes \
-e USE_REVERSE_PROXY=yes \
-e "SERVER_NAME=app1.domain.com app2.domain.com" \
-e app1.domain.com_REVERSE_PROXY_URL=/ \
-e app1.domain.com_REVERSE_PROXY_HOST=http://XXX.XXX.XXX.XXX:XXXX \
-e DISABLED_DEFAULT_SERVER=yes
```

Yet when I start the container I get the following error:
```
[*] Running nginx ...
nginx: [emerg] duplicate location "/" in /etc/nginx/app1.domain.com/reverse-proxy-1.conf:1
[!] nginx failed to start
```

I've read the doc multiple times and I cannot find what I did wrong, can you enlighten me?

**Comment by bunkerity** [comment]
Hello @axeleroy,

You did nothing wrong. The problem is, when using reverse proxy mode, bunkerized-nginx will generate a config like this one : 
```nginx
location / {
	proxy_pass http://A.B.C.D;
}
```

And nginx doesn't allow the use of duplicate location (you also set a **location /**) hence the error you get. Maybe you can try to put your config at server context (without a location block) : 
```nginx
proxy_buffering off;
proxy_cache off;
proxy_http_version 1.1;
chunked_transfer_encoding off;
proxy_set_header Connection '';
```

Please note that you have a typo for **DISABLED_DEFAULT_SERVER**, it should be **DISABLE_DEFAULT_SERVER** (without the 'D').

**Comment by axeleroy** [comment]
Thanks, that works better that way.
