### ISSUE TITLE
[FEATURE] working with php8.0-fpm sock not tcp

### ISSUE THREAD

**Issue by msalmanfarisi** [bunkerity/bunkerized-nginx#150]
How can I add php8.0-fpm and its extensions (such as gd, imap, mysql, pgsql, pdo, etc..) so nginx work with local php-fpm not tcp (REMOTE_PHP) ?
Please help

Thanks

**Comment by fl0ppy-d1sk** [comment]
Hello @msalmanfarisi,

Can you elaborate on your use case ? The current v1.2.7 only supports Docker and the recommended way is to use two containers (one for bunkerized-nginx and another for php-fpm) so they can communicate through an internal network. You have a full example [here](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples/basic-website-with-php).

Anyway, the upcoming v1.3.0 will support standard Linux installation and using the local unix socket instead of TCP might be useful in that case.

**Comment by msalmanfarisi** [comment]
Hello @fl0ppy-d1sk 

I need to pack all into an image. any advise ?
Glad to know the roadmap and hope to get it very soon

**Comment by fl0ppy-d1sk** [comment]
I would suggest you to keep two separated images instead. Keeping this issue open until it's integrated into the next version.

**Comment by msalmanfarisi** [comment]
Hi @fl0ppy-d1sk 
OK. I will keep this issue open.
Thank you for your support

**Comment by fl0ppy-d1sk** [comment]
Hello @msalmanfarisi,

The [v1.3.0 release](https://github.com/bunkerity/bunkerized-nginx/releases/tag/v1.3.0) supports the `LOCAL_PHP` and `LOCAL_PHP_PATH` environment variables. More info [here](https://bunkerized-nginx.readthedocs.io/en/latest/environment_variables.html#php).
