### ISSUE TITLE
Crowdsec can't parse the logs

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerized-nginx#59]
hi,
It seems to have an issue with crowdsec 
find this in logs : 
`time="2020-12-18T23:56:12+01:00" level=info msg="dependency issue crowdsecurity/nginx : missing parsers crowdsecurity/nginx-logs, tainted."`

Thanks

**Comment by bunkerity** [comment]
Hello,

I think CrowdSec just says that because the configuration is manually edited (see [here](https://github.com/bunkerity/bunkerized-nginx/blob/0bc1f652b4acbd325c060ac06d2aff08cd874655/crowdsec/install.sh#L34)).

But there is another problem ! Since the default log format has been changed crowdsec is unable to parse the logs. We need to edit /etc/crowdsec/config/parsers/s01-parse/nginx-logs.yaml : 
```
...
pattern: '(%{IPORHOST:target_fqdn} )?%{IPORHOST:remote_addr} - %{NGUSER:remote_user} %{IPORHOST:server_name} \[%{HTTPDATE:time_local}\] ...
...
```

After editing that config, restarting crowdsec and starting basic attack with a tool like dirb, we can see the ban :  
```
# cscli ban list
1 local decisions:
+--------+----------------+--------------------------------------+------+--------+---------+----+--------+------------+
| SOURCE |       IP       |                REASON                | BANS | ACTION | COUNTRY | AS | EVENTS | EXPIRATION |
+--------+----------------+--------------------------------------+------+--------+---------+----+--------+------------+
| local  | 1.2.3.4 | crowdsecurity/http-crawl-non_statics |    3 | ban    |         |    |     59 | 3h59m31s   |
+--------+----------------+--------------------------------------+------+--------+---------+----+--------+------------+
And 100 records from API, 27 distinct AS, 14 distinct countries
```

**Comment by bunkerity** [comment]
Integrated in the v1.2.2. Huge thanks @thelittlefireman !
