### ISSUE TITLE
Is exists some tricks on how to reduce memory usage?

### ISSUE THREAD

**Issue by zherdev-artem** [bunkerity/bunkerized-nginx#85]
Hi,

I have noticed that the docker container using upon to ~500Mb of RAM as the reverse proxy with 4 proxy items. Of course, it is not precise, just some observation.  Most of the memory is used by BLOCK_REFERRER (~130Mb) and USE_MODSECURITY (~150Mb and more).

I think this issue may be an answer for folks who have the same question. Could you provide some advice on how to reduce memory usage without fully disable these options?

Thanks!

**Comment by bunkerity** [comment]
Hello @zherdev-artem,

I will look into it deeper when I have time but I think it will be hard to reduce the memory usage without turning off the feature especially for ModSecurity.

Please note, since v1.2.3 you can set [custom CRON values](https://github.com/bunkerity/bunkerized-nginx#cron-jobs) for DB/blacklist updates.

**Comment by bunkerity** [comment]
Hello @zherdev-artem,

The last v1.2.5 version includes some performance improvements (at least on the CPU side). There is also a lot of entries inside the proxies list, if you want to disable it you can set `BLOCK_PROXIES=no`.

Do you have some time to test the new version and give us a feedback ?
